# Generated by Django 2.2.1 on 2019-05-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0002_auto_20190524_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinggoods',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Оприходован'),
        ),
    ]
