# Generated by Django 2.2.1 on 2019-05-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0003_postinggoods_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
        migrations.AlterField(
            model_name='postinggoods',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Проведен'),
        ),
    ]
